cloud:
  aws:
    region:
      static: ap-south-1
      auto: false
    stack:
      auto: false
  
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error        